"""Change author to foriegn key

Revision ID: 65e2252ddfa5
Revises: 77cbb1955108
Create Date: 2021-09-14 11:32:24.494533

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '65e2252ddfa5'
down_revision = '77cbb1955108'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'author',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.create_foreign_key(None, 'post', 'users_data', ['author'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.alter_column('post', 'author',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
