"""Updated username

Revision ID: 77cbb1955108
Revises: f65d4136883e
Create Date: 2021-09-13 10:49:03.785472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77cbb1955108'
down_revision = 'f65d4136883e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users_data', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_data', type_='unique')
    # ### end Alembic commands ###
