"""Comment

Revision ID: 9873d2be690e
Revises: 5bd104d377b2
Create Date: 2021-09-14 12:57:14.038160

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9873d2be690e'
down_revision = '5bd104d377b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('author', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
