"""Added author foreign key

Revision ID: b55eac43e655
Revises: 9873d2be690e
Create Date: 2021-09-14 12:59:49.299743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b55eac43e655'
down_revision = '9873d2be690e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('author', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'users_data', ['author'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'author')
    # ### end Alembic commands ###
