"""Removed slug and added publish column to Post model

Revision ID: deff39babb2f
Revises: ad2e4d821e17
Create Date: 2021-09-18 12:07:58.301935

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'deff39babb2f'
down_revision = 'ad2e4d821e17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('published', sa.Boolean(), nullable=False))
    op.drop_column('post', 'slug')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('slug', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('post', 'published')
    # ### end Alembic commands ###
