"""added password field

Revision ID: eff3a8af9ee3
Revises: c9c8c5fa5d88
Create Date: 2021-09-10 11:53:27.000726

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eff3a8af9ee3'
down_revision = 'c9c8c5fa5d88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_data', sa.Column('password_hash', sa.String(length=128), nullable=False))
    op.drop_column('users_data', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_data', sa.Column('password', mysql.VARCHAR(length=32), nullable=False))
    op.drop_column('users_data', 'password_hash')
    # ### end Alembic commands ###
